### ISSUE TITLE
Consider adding a function that allows for `CUSIP` imports

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.portfolio.import#19]
As we work with more American clients, we will increasingly be seeing portfolios with exclusively CUSIP codes, and may need to either: write a function that reads CUSIPs and returns ISINs, OR maintain a separate dataset of CUSIPs (from FactSet for example). 

Julie wrote a cool function that does a decent CUSIP to ISIN conversion already: https://github.com/RMI-PACTA/r2dii.utils/pull/31

**Comment by cjyetman** [comment]
Closing because I don't believe this is feasible. If there is a feasible way, then this can be reopened.
