### ISSUE TITLE
most recent version of Microsoft Excel for Mac does export CSV files with "\r" as the line ending

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.portfolio.import#77]
On Microsoft Excel for Mac v16.81 (presumably the most recent version on my work laptop), when exporting a CSV using the "Macintosh Comma Separated (.csv)" option to export, it creates a file with only "\r" as the line ending (interestingly, in this particular case, it does not add any line ending or newline to the last line).

Similar behavior has been reported over the years (2013-2020)
https://nicercode.github.io/blog/2013-04-30-excel-and-line-endings/
https://answers.microsoft.com/en-us/msoffice/forum/all/excel-office-365-mac-not-saving-utf-8-csv-files/ba44fced-7da7-418c-b230-f24726b8ecf7
https://developmentality.wordpress.com/2010/12/06/excel-2008-for-macs-csv-bug/

Exporting from Excel in this way is something we have advised COP members to do in the recent past.

This suggests to me that getting CSV files that have a line ending with only "\r" at the end is a very real possibility.

Because of this, I think we need to revert #65 and part of #58.

@AlexAxthelm @jdhoffa

**Comment by AlexAxthelm** [comment]
Every time I think things are okay, Excel provides new ways of making life difficult.

![this is fine, dog on fire](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjZyZjZnMGYwMG4weDZsdGJtMzN0NHE2emRhYnh5aG0yeTN2ZzNkaCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/QMHoU66sBXqqLqYvGO/giphy.gif)

**Comment by jdhoffa** [comment]
For posterity, @cjyetman's comment warned of exactly this: https://github.com/RMI-PACTA/pacta.portfolio.import/pull/65#pullrequestreview-1839290062

**Comment by cjyetman** [comment]
I'm aware of the warning, but it's a small price to pay to maintain previous behavior, especially with an impending COP project, and fairly certain memory of having seen files like this in the wild. I'll open am issue to squelch the warning.
